catalog/urls.py
from django.urls import path

from .views import product_list, categoria, produto

urlpatterns = [
    path('', product_list, name='produtos'),
    path('<slug:slug>/', categoria, name='categoria'),
    path('produto/<slug:slug>/', produto, name='produto')

]

djangoecommerce/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from core.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('contato', contact, name='contato'),
    path('entrar/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('sair/', auth_views.LogoutView.as_view(),name='logout'),
    path('catalogo/', include(('catalog.urls','catalog'),namespace='catalog')),
]

catalog/models.py
from django.db import models
from django.urls import reverse


class Categoria(models.Model):

    nome = models.CharField('name',max_length=100)
    slug = models.SlugField('identificador',max_length=100)

    created = models.DateTimeField('criado em',auto_now_add=True)
    modified = models.DateTimeField('modificado em ',auto_now_add=True)

    class Meta:
        verbose_name='Categoria'
        verbose_name_plural = 'Categorias'
        ordering= ['nome']

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('catalog:categoria',kwargs= {'slug':self.slug})


class Produto(models.Model):

    nome = models.CharField('nome',max_length=100)
    slug = models.SlugField('identificador',max_length=100)
    categoria = models.ForeignKey(Categoria,verbose_name='Categoria',on_delete=models.CASCADE)
    descricao = models.TextField('Descrição',blank=True)
    preco = models.DecimalField('Preço', decimal_places=2,max_digits=8)

    created = models.DateTimeField('criado em',auto_now_add=True)
    modified = models.DateTimeField('modificado em ',auto_now_add=True)

    class Meta:
        verbose_name='Produto'
        verbose_name_plural = 'Produtos'
        ordering= ['nome']

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('catalog:produto',kwargs= {'slug':self.slug})

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message= forms.CharField(label='Mensagem',widget=forms.Textarea())


    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = "Nome : {0}\nE-mail : {1}\n{2}".format(name, email, message)

        send_mail(
            'Contato do Django E-commerce', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

catalog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Produto, Categoria
from django.views import generic


class ProductListView(generic.ListView):

    model = Produto
    template_name = 'catalog/products.html'
    context_object_name = 'produtos'
    paginate_by = 3

product_list = ProductListView.as_view()

class CategoriaListView(generic.ListView):
    template_name = 'catalog/categoria.html'
    context_object_name = 'produtos'
    paginate_by = 3

    def get_queryset(self):
        return Produto.objects.filter(categoria__slug=self.kwargs['slug'])

    def get_context_data(self,**kwargs):
        context= super(CategoriaListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Categoria,slug=self.kwargs['slug'])
        return context

categoria = CategoriaListView.as_view()

def produto(request, slug):
    produto = Produto.objects.get(slug=slug)
    context = {
        'produto': produto
    }
    return render(request, 'catalog/product.html', context)

core/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.views.generic import View, TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

index = IndexView.as_view()


def contact(request):
    sucess=False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        sucess = True

    context = {
        'form': form,
        'sucess':sucess
    }
    return render(request, 'contact.html', context)

catalog/templates/catalog/categoria.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
{{current_categoria}} | {{block.super}}
{% endblock  %}

{% block container %}
<div class="container">
    <div class="page-header">
        <h1>{{current_categoria}}</h1>
    </div>
    <div class="row">
        {% for produto in produtos %}
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="{{ produto.get_absolute_url }}">
                    <img src="http://placehold.it/350x250" alt=""/>
                </a>
                <div class="caption">
                    <h3>{{produto}}</h3>
                    {{produto.descricao | linebreaks}}
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.</p>
                    <p><a href="{{ produto.get_absolute_url }}" class="btn btn-success" role="button">Button</a> <a
                            href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% pagination request paginator page_obj %}
{% endblock container %}

catalog/templates/catalog/product.html
{% extends "base.html" %}
{% block title %}
	{{produto}} | {{block.super}}
{% endblock title %}

{% block container %}
	<div class="page-header">
		  <h1>{{produto}}</h1>
		</div>
		<div class="row">
		  <div class="col-sm-4">
			  <a href="{{produto.get_absolute_url}}" class="thumbnail">
				  <img src="http://placehold.it/350x250" alt="" />
			  </a>
		  </div>
		  <div class="col-sm-8">
			  {{ produto.descricao|linebreaks }}
		  </div>
		</div>
	</div>
{% endblock container %}

catalog/templates/catalog/products.html
{% extends "base.html" %}
{% load pagination %}
{% block title %}
Listagem de produto | {{block.super}}
{% endblock  %}

{% block container %}
<div class="container">
    <div class="page-header">
        <h1>Produtos</h1>
    </div>
    <div class="row">
        {% for produto in produtos %}
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="{{ produto.get_absolute_url }}">
                    <img src="http://placehold.it/350x250" alt=""/>
                </a>
                <div class="caption">
                    <h3>{{produto}}</h3>
                    {{produto.descricao | linebreaks}}
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.</p>
                    <p><a href="{{ produto.get_absolute_url }}" class="btn btn-success" role="button">Button</a> <a
                            href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% pagination request paginator page_obj %}
{% endblock container %}

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %} Django e-commerce {% endblock title %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'home' %}" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'home' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                {% for categoria in categorias %}
                <li><a href="{{ categoria.get_absolute_url }}">{{categoria}}</a></li>
                  {%endfor%}
              </ul>
            </li>
			<li>
				<a href="{% url 'contato' %}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Entrar</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
<h1>{{ title|capfirst }}</h1>
    {%block container %}
    {%endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="{%url 'catalog:produtos'%}">Produtos</a></li>
			      <li><a href="{%url 'contato'%}">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}
{% load widget_tweaks %}

{{% block title %}
Contato | {{block.super}}
{% endblock title %}}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if sucess %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso!
    </div>
    {% endif %}
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.erros %}has-error{%endif %}">
                <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{field.label}}</label>
                <div class="col-md-9">
                    {% render_field field class='form-control' %}
                    {% for erro in field.erros %}
                    <span class="hekp-block"></span>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}

            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock container %}

core/templates/index.html
{% extends "base.html" %}

{%block container %}
<div class="jumbotron page-header">
		  <p>Seja bem vindo {{user}}</p>
		  <p><a class="btn btn-primary">Saiba mais</a></p>
</div>
{%endblock %}

core/templates/login.html
{%extends "base.html"%}
{% load widget_tweaks %}
{%block title %} Entrar | {{block.super}}{% endblock %}
{% block container %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h1>Entrar</h1>
            </div>
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{error}}
                </div>
                {% endfor %}
                <fieldset>
                    {% for field in form %}
                    <div class="form-group{% if field.erros %} has-error{%endif %}">
                         <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{field.label}}</label>
                        <div class="col-md-9">
                            {% render_field field class='form-control' %}
                            {% for erro in field.erros %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
{%endblock%}

core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
            <ul class="pagination">
                {% for page in paginator.page_range %}
                <li {% if page_obj.number == page %} class="active"{%endif%}>
                    <a href="?page={{page}}">{{page}}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>

core/templates/products.html
{% extends "base.html" %}

{% block title %}
	Listagem de produto | {{block.super}}
{% endblock  %}

{% block container %}
	       <div class="container">
		<div class="page-header">
			<h1>Produtos</h1>
		</div>
		<div class="row">
			<div class="col-sm-6 col-md-4">
				<div class="thumbnail">
					<a href="#">
						<img src="http://placehold.it/350x250" alt="" />
					</a>
					<div class="caption">
						<h3>Lorem ipsum dolor sit amet</h3>
						<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
						<p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
					</div>
				</div>
			</div>
			<div class="col-sm-6 col-md-4">
	  		    <div class="thumbnail">
	  				<a href="#">
	  					<img src="http://placehold.it/350x250" alt="" />
	  				</a>
	  				<div class="caption">
	  					<h3>Lorem ipsum dolor sit amet</h3>
	  					<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	  					<p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
	  				</div>
	  		    </div>
			</div>
{% endblock container %}